### PR TITLE
More flexible config and some refactoring

### PR DESCRIPTION
**Pull request by infernalmaster**
I wanted to use this with https://github.com/namuol/tap-difflet and did configuration of prettifier independent from this code. So now we can plug any reporter that has separated logic from bin file. And that's why I also did pull request https://github.com/namuol/tap-difflet/pull/9 for https://github.com/namuol/tap-difflet

### CODE REVIEW

**Comment by bySabi** [comment]
Nice!!!!
It looks good!
I will publish it as 3.X.X branch due to breaking changes on `config` API
Thanks!

**Comment by bySabi** [comment]
@infernalmaster current tap-difflet is working with `tap-pretty` ?

**Comment by infernalmaster** [comment]
no. I just did a pull request https://github.com/namuol/tap-difflet/pull/9 to fix this.
And you can also use it option just like that:

```
    tapReporter: {
      get prettify() { return () => require('tap-difflet')({ '--pessimistic': true }); },
      separator: '****************************',
    },
```

**Comment by infernalmaster** [comment]
But you still should apply this fix https://github.com/bySabi/karma-tap-pretty-reporter/pull/9

**Comment by bySabi** [comment]
I reject PR: 9 but add it manually on my local repo. 

I asked you about tap-difflet for update `supported prettifiers` on README.

When your tap-difflet get merged I will update supported prettifiers Doc.

I update master branch in preparation to publish npm version 3.0.0 ... take a look before publish it

**Comment by bySabi** [comment]
I test it with latest `tap-difflet` release and  is working fine. Added to supported prettifiers on README

Thanks.

**Comment by bySabi** [comment]
@infernalmaster are you interested on code coverage using https://github.com/istanbuljs, and karma?
I want update current `karma-coverage` package or create a new one more in the line of `nyc` istanbul tool and his new API. 
You are interested in joining forces on this subject?

**Comment by infernalmaster** [comment]
Yes, I'm interest on this subject, but I don't have much experience with node API. I usually work with js in browser. But I'm ready to help you with this.

By the way now karma-tap-pretty-reporter works with https://github.com/namuol/tap-difflet/tree/0.7.0

**Comment by bySabi** [comment]
@infernalmaster I create a karma coverage reporter based on Istanbul new v1 API.
Any feedback is welcome.

https://github.com/bySabi/karma-istanbuljs-reporter

**Pull request merged**
